core/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('knowledge_pool.urls', namespace='knowledge_pool')),
    url(r'^users/', include('users.urls', namespace='users')),
]

knowledge_pool/urls.py
""" Define as urls do knowledge_pool """

from django.conf.urls import url

from . import views

urlpatterns = [
    # Página inicial
    url(r'^$', views.index, name='index'),

    # Página sobre
    url(r'^about$', views.about, name='about'),

    # Página com todos os assuntos
    url(r'^assuntos$', views.assuntos, name='assuntos'),

    # Página com um assunto e suas entradas
    url(r'^assuntos/(?P<assunto_id>\d+)/$', views.assunto, name='assunto'),

    # Página para um novo assunto
    url(r'^novo_assunto/$', views.novo_assunto, name='novo_assunto'),

    # Deletar um assunto
    url(r'^remover_assunto/(?P<assunto_id>\d+)/$',
        views.remover_assunto, name='remover_assunto'),

    # Confirma remocao assunto
    url(r'^confirma_remocao_assunto/(?P<assunto_id>\d+)/$',
        views.confirma_remocao_assunto, name='confirma_remocao_assunto'),

    # Editar um assunto
    url(r'^editar_assunto/(?P<assunto_id>\d+)/$',
        views.editar_assunto, name='editar_assunto'),

    # Página para uma nova entrada sobre um assunto específico
    url(r'^nova_entrada/(?P<assunto_id>\d+)/$',
        views.nova_entrada, name='nova_entrada'),

    # Páginas para editar entradas sobre um assunto
    url(r'^editar_entrada/(?P<entrada_id>\d+)/$',
        views.editar_entrada, name='editar_entrada'),

    # Confirma remocao entrada
    url(r'^confirma_remocao_entrada/(?P<entrada_id>\d+)/$',
        views.confirma_remocao_entrada, name='confirma_remocao_entrada'),

    # Deletar uma entrada
    url(r'^remover_entrada/(?P<entrada_id>\d+)/$',
        views.remover_entrada, name='remover_entrada'),

    # Apresenta os gráficos.
    url(r'^graficos$', views.graficos, name='graficos'),

    # Entradas do user
    url(r'^minhas_entradas/(?P<user_id>\d+)/$',
        views.minhas_entradas, name='minhas_entradas'),

    # Soma utilização
    url(r'^soma_utilizacao/(?P<entrada_id>\d+)/$', views.soma_utilizacao, name='soma_utilizacao'),

    # Mostra Entradas mais utilizadas
    url(r'^entradas_utilizadas$', views.entradas_utilizadas, name='entradas_utilizadas'),
]

users/urls.py
""" Urls para users """

from django.conf.urls import url
from django.contrib.auth.views import login

from . import views

urlpatterns = [
    # Página de login
    url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),

    # Página de logout
    url(r'^logout/$', views.logout_view, name='logout'),

    # Página de cadastro
    url(r'^register/$', views.register, name='register'),
]

knowledge_pool/models.py
""" Models da app Knowledge_Pool"""
from django.db import models
from django.contrib.auth.models import User


class Assunto(models.Model):
    """ Classe que representa uma assunto """
    titulo = models.CharField(max_length=200)
    descricao = models.TextField()
    data_criacao = models.DateTimeField(auto_now_add=True)
    dono = models.ForeignKey(User)
    qnt_entradas = models.IntegerField(default=0)

    def __str__(self):
        """ Devolve o titulo do assunto """
        return self.titulo


class Entrada(models.Model):
    """ Classe que define uma entrada sobre um assunto """
    assunto = models.ForeignKey(Assunto)
    ticket_associado = models.CharField(max_length=50, blank=True)
    texto = models.TextField()
    data_criacao = models.DateTimeField(auto_now_add=True)
    dono = models.ForeignKey(User)
    qtd_utilizacoes = models.IntegerField(default=0)

    def __str__(self):
        """ Retorna uma representação do assunto. """
        if len(self.texto) > 50:
            return self.texto[:50] + "..."
        else:
            return self.texto

knowledge_pool/forms.py
""" Arquivo de formulário para knowledge_pool """

from django import forms

from .models import Assunto, Entrada


class AssuntoForm(forms.ModelForm):
    """ Classe que define um form para o modelo Assunto """
    class Meta:
        """ Classe de dados do Modelo assunto (transforma em campos) """
        model = Assunto
        fields = ['titulo', 'descricao']
        labels = {'titulo': 'Título', 'descricao': 'Descrição'}


class EntradaForm(forms.ModelForm):
    """ Classe que define um form baseado no modelo Entrada """
    class Meta:
        """ define os campos do form baseada nos atributos do modelo """
        model = Entrada
        fields = ['ticket_associado', 'texto']
        labels = {'texto': 'Texto', 'ticket_associado': 'Ticket/Erro'}
        widgets = {'texto': forms.Textarea(attrs={'cols': 80})}

knowledge_pool/views.py
""" Arquivo de views(controller) do app knowledge_pool """
import json

from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render

from .forms import AssuntoForm, EntradaForm
from .models import Assunto, Entrada
from .utils import *


def index(request):
    """ Retorna página Inicial """
    try:
        user = User.objects.get(id=request.user.id)
        context = {'user': user}
        return render(request, 'knowledge_pool/index.html', context)
    except ObjectDoesNotExist:
        return render(request, 'knowledge_pool/index.html')


def about(request):
    """ About page """
    try:
        user = User.objects.get(id=request.user.id)
        contexto = {'user': user}
        return render(request, 'knowledge_pool/about.html', contexto)
    except ObjectDoesNotExist:
        return render(request, 'knowledge_pool/about.html')


@login_required
def assuntos(request):
    """ Retorna uma página com todos os assuntos """
    lista_assuntos = Assunto.objects.order_by('data_criacao')
    contexto = {'lista_assuntos': lista_assuntos}
    return render(request, 'knowledge_pool/assuntos.html', contexto)


@login_required
def assunto(request, assunto_id):
    """ Retorna um assunto e todas as suas entradas """
    var_assunto = Assunto.objects.get(id=assunto_id)
    user_logado = User.objects.get(id=request.user.id)

    entradas = var_assunto.entrada_set.order_by('-data_criacao')
    contexto = {'assunto': var_assunto, 'entradas': entradas,
                'user_logado': user_logado}
    return render(request, 'knowledge_pool/assunto.html', contexto)


@login_required
def novo_assunto(request):
    """ Cria um novo assunto """
    if request.method != 'POST':
        form = AssuntoForm()
    else:
        form = AssuntoForm(request.POST)
        if form.is_valid():
            novo_assunto = form.save(commit=False)
            novo_assunto.dono = request.user
            novo_assunto.save()
            return HttpResponseRedirect(reverse('knowledge_pool:assuntos'))
    contexto = {'form': form}
    return render(request, 'knowledge_pool/novo_assunto.html', contexto)


@login_required
def editar_assunto(request, assunto_id):
    """ Editar um assunto """
    assunto = Assunto.objects.get(id=assunto_id)

    if request.method != 'POST':
        # Entrega um form com os dados atuais
        form = AssuntoForm(instance=assunto)
    else:
        # Dados submetidos, processa e salva alteração
        form = AssuntoForm(instance=assunto, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('knowledge_pool:assunto', args=[assunto.id]))

    contexto = {'assunto': assunto, 'form': form}
    return render(request, 'knowledge_pool/editar_assunto.html', contexto)


@login_required
def confirma_remocao_assunto(request, assunto_id):
    """ Confirma a remocao de um assunto """
    assunto = Assunto.objects.get(id=assunto_id)
    contexto = {'assunto': assunto}
    return render(request, 'knowledge_pool/confirma_remocao_assunto.html', contexto)


@login_required
def remover_assunto(request, assunto_id):
    """ Remove um assunto """
    assunto = Assunto.objects.get(id=assunto_id)
    assunto.delete()
    return HttpResponseRedirect(reverse('knowledge_pool:assuntos'))


@login_required
def nova_entrada(request, assunto_id):
    """ Cria uma nova entrada sobre um assunto em específico """
    assunto = Assunto.objects.get(id=assunto_id)
    user_logado = User.objects.get(id=request.user.id)

    if request.method != 'POST':
        # Nenhum dado submetido, retorna form em branco.
        form = EntradaForm()
    else:
        # Dados de post submetidos, processa o form.
        form = EntradaForm(data=request.POST)
        if form.is_valid():
            nova_entrada = form.save(commit=False)
            assunto.qnt_entradas += 1
            nova_entrada.assunto = assunto
            nova_entrada.dono = user_logado
            assunto.save()
            nova_entrada.save()

            return HttpResponseRedirect(
                reverse('knowledge_pool:assunto', args=[assunto_id]))
    contexto = {'assunto': assunto, 'form': form}
    return render(request, 'knowledge_pool/nova_entrada.html', contexto)


@login_required
def editar_entrada(request, entrada_id):
    """ Edita uma entrada existente """
    entrada = Entrada.objects.get(id=entrada_id)
    assunto = entrada.assunto

    if request.method != 'POST':
        # Requição inicial, entrega um form com os dados da entrada preenchidos
        form = EntradaForm(instance=entrada)
    else:
        # Dados de post submetidos, processa os dados
        form = EntradaForm(instance=entrada, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(
                reverse('knowledge_pool:assunto', args=[assunto.id]))
    contexto = {'entrada': entrada, 'assunto': assunto, 'form': form}
    return render(request, 'knowledge_pool/editar_entrada.html', contexto)


@login_required
def confirma_remocao_entrada(request, entrada_id):
    """ Confirma a remocao de uma entrada """
    entrada = Entrada.objects.get(id=entrada_id)
    contexto = {'entrada': entrada}
    return render(request, 'knowledge_pool/confirma_remocao_entrada.html', contexto)


@login_required
def remover_entrada(request, entrada_id):
    """ Remove uma entrada """
    entrada = Entrada.objects.get(id=entrada_id)
    assunto = Assunto.objects.get(id=entrada.assunto_id)
    entrada.delete()
    if entrada is not None:
        return HttpResponseRedirect(
            reverse('knowledge_pool:assunto', args=[entrada.assunto.id]))
    else:
        contexto = {"assunto": assunto.id}
        return render(request, 'knoledge_pool/assunto.html', contexto)

@login_required
def graficos(request):
    """ Apresenta os gráficos """
    qtd_entradas = get_qnt_entrada()
    titulos_assuntos = get_titulos_assuntos()
    user_names = get_user_names()
    entradas_por_user = get_entradas_por_user()
    entradas_utilizadas = get_entradas_utilizadas_chart()

    contexto = {"titulos": json.dumps(titulos_assuntos),
                "entradas": json.dumps(qtd_entradas),
                "users": json.dumps(user_names),
                "entradas_por_user": json.dumps(entradas_por_user),
                "assuntos_entradas": json.dumps(entradas_utilizadas['assuntos']),
                "qnt_entradas_utilizadas": json.dumps(entradas_utilizadas['qnt']),
                "entradas_utilizadas": get_entradas_utilizadas()}

    return render(request, 'knowledge_pool/graficos.html', contexto)


@login_required
def minhas_entradas(request, user_id):
    """ Mostra as entradas do user logado """
    user = User.objects.get(id=user_id)
    entradas = user.entrada_set.all()
    assuntos_all = [obj.assunto for obj in entradas]
    assuntos = []
    for assunto in assuntos_all:
        if assunto not in assuntos:
            assuntos.append(assunto)
    contexto = {"user": user,
                "entradas": entradas,
                "assuntos": assuntos}
    return render(request, 'knowledge_pool/minhas_entradas.html', contexto)


@login_required
def soma_utilizacao(request, entrada_id):
    """ Soma 1 na utilização de uma entrada """
    entrada = Entrada.objects.get(id=entrada_id)
    assunto = entrada.assunto
    entrada.qtd_utilizacoes += 1
    entrada.save()
    return HttpResponseRedirect(
        reverse('knowledge_pool:assunto', args=[assunto.id]))


@login_required
def entradas_utilizadas(request):
    """ Mostra as entradas mais utilizadas """
    entradas = get_entradas_utilizadas()
    contexto = {"entradas": entradas}
    return render(request, 'knowledge_pool/entradas_utilizadas.html', contexto)

knowledge_pool/templates/knowledge_pool/assunto.html
{% extends "knowledge_pool/base.html" %} {% block header %}
<h2>{{ assunto }}</h2>
<p>{{ assunto.descricao }}</p>
<p>Quantidade de entradas: {{ assunto.qnt_entradas }}</p>
{% if user_logado == assunto.dono %}
<a href="{% url 'knowledge_pool:editar_assunto' assunto.id %}">Editar/Remover</a>
{% endif %} {% endblock header %} {% block content %}
<p>
    <a href="{% url 'knowledge_pool:nova_entrada' assunto.id %}">Nova entrada</a>
</p>

{% for entrada in entradas %}
<div class="panel panel-default">
    <div class="panel-heading">
        <h4>
            Criada em: {{ entrada.data_criacao|date:'d/M/Y, H:i' }} por {{ entrada.dono.username }} 
            {% if user_logado == entrada.dono %}
            <small>
                <a href="{% url 'knowledge_pool:editar_entrada' entrada.id %}">Editar/Remover</a>
            </small>
            {% endif %}
            <div class="pull-right">
                <h6>
                    <form>
                        Utilizada {{ entrada.qtd_utilizacoes }} vezes
                        <button type="submit" class="btn btn-info btn-xs" formaction="{% url 'knowledge_pool:soma_utilizacao' entrada.id %}">
                            +
                        </button>
                    </form>
                </h6>
            </div>
        </h4>
    </div>
    <div class="panel-body">
        {% if entrada.ticket_associado != '' %}
        <h4>Ticket/Erro associado: {{ entrada.ticket_associado }}</h4>
        <br/> {% endif %} {{ entrada.texto|linebreaks }}
    </div>
</div>
<!-- panel -->
{% empty %} Não há entradas para este tópico ainda. {% endfor %}
<!-- Modal -->

{% endblock content %}

knowledge_pool/templates/knowledge_pool/assuntos.html
{% extends "knowledge_pool/base.html" %} {% block header %}
<h1>Assuntos</h1>
{% endblock header %} {% block content %}
<ul>
  {% for assunto in lista_assuntos %}
  <li>
    <h3>
      <a href="{% url 'knowledge_pool:assunto' assunto.id %}">
        {{ assunto }}
      </a>
    </h3>
  </li>
  {% empty %}
  <li>Nenhum assunto cadastrado até o momento.</li>
  {% endfor %}
</ul>
<br />
<h4>
  <a href="{% url 'knowledge_pool:novo_assunto' %}">Novo assunto</a>
</h4>

{% endblock content %}

knowledge_pool/templates/knowledge_pool/base.html
{% load bootstrap3 %} {% load static %} {% load staticfiles %}


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'knowledge_pool/css/bootstrap.min.css' %}">

    <link rel="stylesheet" href="{% static 'knowledge_pool/css/knowledge_pool.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.0/Chart.min.js"></script>
    <script src="{% static 'knowledge_pool/js/chart_functions.js' %}"></script>
    <!--<script src="{% static " knowledge_pool/js/Chart.min.js " %}"></script>-->
    <!--<script src="{% static 'knowledge_pool/js/jquery.js' %}"></script>-->
    {% if user.is_authenticated %}
    <title>Knowledge Pool | {{ user.username }}</title>
    {% else %}
    <title>Knowledge Pool</title>
    {% endif %} {% bootstrap_css %} {% bootstrap_javascript %} {% block header-links %} {% endblock header-links %}
</head>

<body>
    <!-- Static Navbar -->
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false"
                    aria-controls="navbar">
                </button>
                <a class="main-title" href="{% url 'knowledge_pool:index' %}">
                    KnowledgePool
                </a>
            </div>

            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{% url 'knowledge_pool:assuntos' %}">Assuntos</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li>
                        <a href="{% url 'knowledge_pool:graficos' %}">Gráficos Informativos</a>
                    </li>
                    <li>
                        <a href="{% url 'knowledge_pool:minhas_entradas' user.id %}">Minhas Entradas</a>
                    </li>
                    <li>
                        <a href="{% url 'knowledge_pool:entradas_utilizadas' %}">Entradas mais utilizadas</a>
                    </li>
                    <li>
                        <a href="{% url 'knowledge_pool:about' %}">About</a>
                    </li>
                    {% endif %}
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                    <li>
                        <a>Olá, {{ user.username }}.</a>
                    </li>
                    <li>
                        <a href="{% url 'users:logout' %}">Log out</a>
                    </li>
                    {% else %}
                    <li>
                        <a href="{% url 'users:register' %}">Cadastro</a>
                    </li>
                    <li>
                        <a href="{% url 'users:login' %}">Log in</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
            <!-- /.nav collapse -->
        </div>
    </nav>

    <div class="container">
        <div class="page-header">
            {% block header %} {% endblock header %}
        </div>
        <div>
            {% block content %} {% endblock content %}
        </div>
        <div>
            {% block scripts %} {% endblock scripts %}
        </div>
    </div>
    <!-- /container -->
    <footer class="footer">
        <div class="container">
            <p class="text-muted">
                Copyright &copy; Knowledge Pool 2017 -
                <a href="https://github.com/tv-nieri/knowledge_pool">Github</a>
            </p>
        </div>
    </footer>
</body>

</html>

knowledge_pool/templates/knowledge_pool/confirma_remocao_assunto.html
{% extends "knowledge_pool/base.html" %} {% load bootstrap3 %} {% block header %}
<h2>Deseja mesmo remover {{ assunto }} e todas as suas entradas?</h2>
{% endblock header %} {% block content %}
<div class="panel panel-default">
    <div class="panel-heading">
        <h3>Detalhes do assunto</h3>
    </div>
    <div class="panel-body">
        <h4>
            <p>Adicionado por: {{ assunto.dono.username }}</p>
            <p>Data de criação: {{ assunto.data_criacao }}</p>
            Descrição:
            <p>{{assunto.descricao}}</p>
        </h4>
    </div>
</div>
<!-- panel -->
<form action="#">
    {% buttons %}
    <button type="submit" name="remove" class="btn btn-danger" formaction="{% url 'knowledge_pool:remover_assunto' assunto.id %}">
        Remover
    </button>
    <button type="submit" name="back" class="btn btn-info" formaction="{% url 'knowledge_pool:editar_assunto' assunto.id %}">
        Voltar
    </button>
    {% endbuttons %}
</form>
{% endblock content %}

knowledge_pool/templates/knowledge_pool/confirma_remocao_entrada.html
{% extends "knowledge_pool/base.html" %} {% load bootstrap3 %} {% block header %}
<h2>Deseja mesmo remover esta entrada?</h2>
{% endblock header %} {% block content %}
<div class="panel panel-default">
    <div class="panel-heading">
        <h3>Detalhes da Entrada</h3>
    </div>
    <div class="panel-body">
        <h4>
            <p>Adicionado por: {{ entrada.dono.username }}</p>
            <p>Data de criação: {{ entrada.data_criacao }}</p>
            Descrição:
            <p>{{entrada.texto}}</p>
        </h4>
    </div>
</div>
<!-- panel -->
<form action="#">
    {% buttons %}
    <button type="submit" name="remove" class="btn btn-danger" formaction="{% url 'knowledge_pool:remover_entrada' entrada.id %}">
        Remover
    </button>
    <button type="submit" name="back" class="btn btn-info" formaction="{% url 'knowledge_pool:editar_entrada' entrada.id %}">
        Voltar
    </button>
    {% endbuttons %}
</form>
{% endblock content %}

knowledge_pool/templates/knowledge_pool/editar_assunto.html
{% extends "knowledge_pool/base.html" %} {% load bootstrap3 %} {% block header %}
<h2>{{ assunto }}</h2>
{% endblock header %} {% block content %}

<form action="{% url 'knowledge_pool:editar_assunto' assunto.id %}" method="POST" class="form">
    {% csrf_token %} {% bootstrap_form form %} {% buttons %}
    <button type="submit" name="submit" class="btn btn-primary">
        Salvar anterações
    </button>
    <button type="submit" name="remove" class="btn btn-danger" formaction="{% url 'knowledge_pool:confirma_remocao_assunto' assunto.id %}">
        Remover
    </button>
    {% endbuttons %}
</form>

{% endblock content %}

knowledge_pool/templates/knowledge_pool/editar_entrada.html
{% extends "knowledge_pool/base.html" %} {% load bootstrap3 %} {% block header %}
<h2>
    Editar entrada para
    <a href="{% url 'knowledge_pool:assunto' assunto.id %}">
        {{ assunto }}
    </a>:
</h2>
{% endblock header %} {% block content %}

<form action="{% url 'knowledge_pool:editar_entrada' entrada.id %}" method="POST" class="form">
    {% csrf_token %} {% bootstrap_form form %} {% buttons %}
    <button type="submit" name="submit" class="btn btn-primary">
        Salvar alterações
    </button>
    <button type="submit" name="remove" class="btn btn-danger" formaction="{% url 'knowledge_pool:confirma_remocao_entrada' entrada.id %}">
        Remover
    </button>
    {% endbuttons %}
</form>

{% endblock content %}

knowledge_pool/templates/knowledge_pool/entradas_utilizadas.html
{% extends 'knowledge_pool/base.html' %} {% block header %}
<h1>Entradas mais utilizadas</h1>
<h6>
    Clique sobre o assunto para ir até sua página.
</h6>
{% endblock header %} {% block content %}
<div class="panel panel-default, panel panel-primary">

    {% for entrada in entradas %}


    <div class="panel-body">
        <div class="list-group">

            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="pull-right">
                        <a href="{% url 'knowledge_pool:assunto' entrada.assunto.id %}">
                            Em: {{ entrada.assunto.titulo }}
                        </a>
                    </div>
                    Criada em: {{ entrada.data_criacao }}, por {{ entrada.dono }}
                </div>
                <div class="panel-body">
                    {{ entrada.texto }}
                </div>

            </div>

        </div>
    </div>

    {% endfor %}
</div>

{% endblock content %}

knowledge_pool/templates/knowledge_pool/graficos.html
{% extends 'knowledge_pool/base.html' %} {% load bootstrap3 %} {% load staticfiles %} {% load static %} {% block header %}
<h2>Gráficos disponíveis</h2>
{% endblock header %} {% block content %}

<div class="panel panel-default">
    <div class="panel-heading">
        <h4>Assuntos com maior número de entradas</h4>
        <small>mostra os assuntos que mais recebem entradas.</small>
    </div>
    <div class="panel-body" id="chart_canvas">
        <div class="col-md-10">
            <canvas id="assuntosComMaisEntradas"></canvas>
        </div>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <h4>Entradas mais utilizadas</h4>
        <small>mostra as entradas que mais ajudaram a resolver problemas recorrentes.</small>
        <div class="pull-right">
            <a href="{% url 'knowledge_pool:entradas_utilizadas' %}" alt="entradas">Ver entradas mais utilizadas</a>
        </div>
    </div>
    <div class="panel-body" id="chart_canvas">
        <div class="col-md-10">
            <canvas id="entradasMaisUtilizadas"></canvas>
        </div>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <h4>Maiores Contribuidores</h4>
        <small>mostra os membros do time que mais contribuem para o crescimento da base.</small>
    </div>
    <div class="panel-body" id="chart_canvas">
        <div class="col-md-10">
            <canvas id="usersComMaisEntradas"></canvas>
        </div>
    </div>
</div>

{% endblock content %} {% block scripts %}
<!-- Gráfico de assuntos com maior número de entradas -->
<script>
    getVerticalBarChart("assuntosComMaisEntradas", '{{ titulos|safe }}', '{{ entradas|safe }}', "# Entradas por Assunto");
    getVerticalBarChart("usersComMaisEntradas", '{{ users|safe }}', '{{ entradas_por_user|safe }}', "# Qtd de entradas");
    getVerticalBarChart("entradasMaisUtilizadas", '{{ assuntos_entradas|safe }}', '{{ qnt_entradas_utilizadas|safe }}', "# Entradas mais utilizadas")
</script> {% endblock scripts %}

knowledge_pool/templates/knowledge_pool/index.html
{% extends "knowledge_pool/base.html" %} {% block header %}
<div class="jumbotron">
    <h1 class="main-title">
        <center> Knowledge Pool</center>
    </h1>
</div>
{% endblock header %} {% block content %} {% if user.is_authenticated %}
<h2>Bem vindo {{ user }}!!!</h2>
{% else %}
<h2>
    <a href="{% url 'users:register' %}">Crie uma conta</a> para consultar assuntos e criar sua próprias anotações.
</h2>
{% endif %}

<h2>
    Aqui você pode pesquisar sobre um assunto específico sobre o qual está aprendendo ou encontrar uma solução para um problema
    que encontrou. Mas é claro, é importante compartilhar o que você sabe também, então não deixe de criar suas próprias
    anotações!
    <a href="{% url 'knowledge_pool:assuntos' %}">Começar!</a>
    <br/>
    <br/>
    <i>"Se quer ir rápido vá sozinho. Se quer ir longe, vamos juntos..."</i>
</h2>
{% endblock content %}

knowledge_pool/templates/knowledge_pool/minhas_entradas.html
{% extends 'knowledge_pool/base.html' %} {% block header %}
<h1>Minhas entradas:</h1>
<h6>
    Clique sobre a entrada para editá-la, ou clique sobre o assunto para ir até sua página.
</h6>
{% endblock header %} {% block content %} {% for assunto in assuntos %}
<div class="panel panel-default, panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">
            Em:
            <a href="{% url 'knowledge_pool:assunto' assunto.id %}">{{ assunto.titulo }}</a>
        </h3>
    </div>
    <div class="panel-body">
        <div class="list-group">
            {% for entrada in entradas %} 
                {% if entrada.assunto == assunto %} Criada em: {{ entrada.data_criacao }}
                <a href="{% url 'knowledge_pool:editar_entrada' entrada.id %}" class="list-group-item">
                    {{ entrada.texto }}
                </a>
                <br/> 
                {% endif %} 
            {% endfor %}
        </div>
    </div>
</div>
{% endfor %} {% endblock content %}

knowledge_pool/templates/knowledge_pool/nova_entrada.html
{% extends "knowledge_pool/base.html" %} {% load bootstrap3 %} {% block header %}
<h2>
    Nova entrada para
    <a href="{% url 'knowledge_pool:assunto' assunto.id %}">{{ assunto }}</a>:
</h2>
{% endblock header %} {% block content %}

<form action="{% url 'knowledge_pool:nova_entrada' assunto.id %}" method="POST" class="form">
    {% csrf_token %} {% bootstrap_form form %} {% buttons %}
    <button name="submit" class="btn btn-primary">Adicionar</button>
    {% endbuttons %}
</form>

{% endblock content %}

knowledge_pool/templates/knowledge_pool/novo_assunto.html
{% extends "knowledge_pool/base.html" %} {% load bootstrap3 %} {% block header %}
<h2>Adicionar um novo assunto:</h2>
{% endblock header %} {% block content %}

<form action="{% url 'knowledge_pool:novo_assunto' %}" method="POST" class="form">
  {% csrf_token %} {% bootstrap_form form %} {% buttons %}
  <button name="submit" class="btn btn-primary">Adicionar</button>
  {% endbuttons %}

</form>

{% endblock content %}